[package]
categories = ["config", "network-programming", "web-programming"]
description = "Light Web Kit"
edition = "2024"
homepage = "https://github.com/CloverOS/nano-rs"
keywords = ["auto-route", "config", "http", "web"]
license = "MIT"
name = "nano-rs-extra"
readme = "README.md"
repository = "https://github.com/CloverOS/nano-rs"
rust-version = "1.94.0"
version = "0.1.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
axum-client-ip = { workspace = true }
http-body-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt", "signal"] }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }

bytes = { workspace = true }
log = { workspace = true, optional = true }
uuid = { workspace = true }

prettyplease = "0.3.0"
proc-macro2 = "1.0.107"
quote = { version = "1.0.47", features = ["default"] }
syn = { version = "3.0.3", features = ["full"] }

nano-rs-build = { path = "../nano-rs-build" }
nano-rs-core = { path = "../nano-rs-core" }
sea-orm = { version = "2", default-features = false, optional = true, features = [
    "macros",
    "runtime-tokio-rustls",
    "with-bigdecimal",
    "with-chrono",
    "with-json",
    "with-rust_decimal",
    "with-time",
    "with-uuid",
] }
utoipa = { workspace = true, optional = true }

[features]
default = []
mysql = ["dep:log", "dep:sea-orm", "sea-orm/sqlx-mysql"]
postgres = ["dep:log", "dep:sea-orm", "sea-orm/sqlx-postgres"]
utoipa_axum = ["dep:utoipa"]

[dev-dependencies]
futures-util = { version = "0.3.33", default-features = false }
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }
