/// Code generated by nano-rs. DO NOT EDIT.
use nano_rs::axum::generator::gen_api_info::ApiInfo;
#[allow(dead_code)]
pub fn get_api_info() -> Vec<ApiInfo> {
    vec![
        ApiInfo { method : "get".to_owned(), path : "/samoyed/name".to_owned(), base_path
        : "".to_owned(), handler_fun : "name".to_owned(), summary : "Get Samoyed name"
        .to_owned(), public : false, group_name : "Samoyed".to_owned(), }, ApiInfo {
        method : "post".to_owned(), path : "/samoyed/shower".to_owned(), base_path : ""
        .to_owned(), handler_fun : "shower".to_owned(), summary :
        "Give your Samoyed a bath".to_owned(), public : false, group_name : "Samoyed"
        .to_owned(), }, ApiInfo { method : "post".to_owned(), path : "/store/pet/form"
        .to_owned(), base_path : "".to_owned(), handler_fun : "handler".to_owned(),
        summary : "Add a new pet to the store(form)".to_owned(), public : false,
        group_name : "Store".to_owned(), }, ApiInfo { method : "post".to_owned(), path :
        "/store/pet/json".to_owned(), base_path : "".to_owned(), handler_fun : "handler"
        .to_owned(), summary : "Add a new pet to the store(json)".to_owned(), public :
        false, group_name : "Store".to_owned(), }, ApiInfo { method : "get".to_owned(),
        path : "/store/pet/{id}".to_owned(), base_path : "".to_owned(), handler_fun :
        "handler".to_owned(), summary : "Get pet by id".to_owned(), public : false,
        group_name : "Store".to_owned(), }, ApiInfo { method : "get".to_owned(), path :
        "/store/name".to_owned(), base_path : "".to_owned(), handler_fun : "handler"
        .to_owned(), summary : "Get store name".to_owned(), public : false, group_name :
        "Store".to_owned(), }, ApiInfo { method : "get".to_owned(), path : "/store/tel"
        .to_owned(), base_path : "".to_owned(), handler_fun : "handler".to_owned(),
        summary : "Get Store's telephone number".to_owned(), public : false, group_name :
        "Store".to_owned(), }, ApiInfo { method : "post".to_owned(), path :
        "/store/pet/page-data/{page}/{count}".to_owned(), base_path : "".to_owned(),
        handler_fun : "handler".to_owned(), summary :
        "Get pet list with page data wrapper".to_owned(), public : false, group_name :
        "Store".to_owned(), }, ApiInfo { method : "post".to_owned(), path :
        "/store/pet/list/{page}/{count}".to_owned(), base_path : "".to_owned(),
        handler_fun : "handler".to_owned(), summary : "Get pet list".to_owned(), public :
        false, group_name : "Store".to_owned(), }, ApiInfo { method : "get".to_owned(),
        path : "/store/pet".to_owned(), base_path : "".to_owned(), handler_fun :
        "handler".to_owned(), summary : "Query pet by id".to_owned(), public : false,
        group_name : "Store".to_owned(), }
    ]
}
