/// Code generated by nano-rs. DO NOT EDIT.
use utoipa::OpenApi;
#[utoipa::path(
    get,
    path = "/samoyed/name",
    tag = "Samoyed",
    summary = "Get Samoyed name",
    responses(
        (status = 200, body = String),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_0_name() {}
#[utoipa::path(
    post,
    path = "/samoyed/shower",
    tag = "Samoyed",
    summary = "Give your Samoyed a bath",
    responses(
        (status = 200, body = example_modular_model::PetShower),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_1_shower() {}
#[utoipa::path(
    post,
    path = "/store/pet/form",
    tag = "Store",
    summary = "Add a new pet to the store(form)",
    request_body(
        content = example_modular_model::PetForm,
        content_type = "application/x-www-form-urlencoded"
    ),
    responses(
        (status = 200, body = example_modular_model::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_2_add_form_pet() {}
#[utoipa::path(
    post,
    path = "/store/pet/json",
    tag = "Store",
    summary = "Add a new pet to the store(json)",
    request_body = example_modular_model::Pet,
    responses(
        (status = 200, body = example_modular_model::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_3_add_json_pet() {}
#[utoipa::path(
    get,
    path = "/store/pet/{id}",
    tag = "Store",
    summary = "Get pet by id",
    params(example_modular_model::Params),
    responses(
        (status = 200, body = example_modular_model::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_4_get_pet() {}
#[utoipa::path(
    get,
    path = "/store/name",
    tag = "Store",
    summary = "Get store name",
    responses(
        (status = 200, body = String),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_5_get_store_name() {}
#[utoipa::path(
    get,
    path = "/store/tel",
    tag = "Store",
    summary = "Get Store's telephone number",
    responses(
        (status = 200, body = String),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_6_get_store_tel() {}
#[utoipa::path(
    post,
    path = "/store/pet/list/{page}/{count}",
    tag = "Store",
    summary = "Get pet list",
    params(example_modular_model::Page),
    responses(
        (status = 200, body = Vec<example_modular_model::Pet>),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_7_pet_page_list() {}
#[utoipa::path(
    get,
    path = "/store/pet",
    tag = "Store",
    summary = "Query pet by id",
    params(example_modular_model::QueryPet),
    responses(
        (status = 200, body = example_modular_model::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_8_query_pet() {}
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Modular Pet",
        description = "Modular nano-rs example",
        version = "v1",
        license(name = "", url = ""),
        contact(name = "Modular Team", email = "modular@example.com", url = ""),
    ),
    paths(
        __nano_auto_doc_0_name,
        __nano_auto_doc_1_shower,
        __nano_auto_doc_2_add_form_pet,
        __nano_auto_doc_3_add_json_pet,
        __nano_auto_doc_4_get_pet,
        __nano_auto_doc_5_get_store_name,
        __nano_auto_doc_6_get_store_tel,
        __nano_auto_doc_7_pet_page_list,
        __nano_auto_doc_8_query_pet
    ),
    components(
        schemas(
            example_modular_model::Meta,
            example_modular_model::Pet,
            example_modular_model::PetForm,
            example_modular_model::PetShower
        )
    ),
    servers((url = "http://127.0.0.1:8899", description = "dev")),
    tags()
)]
pub struct GenApi {}
