[package]
categories = ["config", "network-programming", "web-programming"]
description = "Light Web Kit"
edition = "2024"
homepage = "https://github.com/CloverOS/nano-rs"
keywords = ["auto-route", "config", "http", "web"]
license = "MIT"
name = "nano-rs"
readme = "README.md"
repository = "https://github.com/CloverOS/nano-rs"
rust-version = "1.88.0"
version = "0.1.4"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nano-rs-core = { path = "../nano-rs-core" }
#nano-rs-rpc = { path = "../nano-rs-rpc" }
nano-rs-build = { path = "../nano-rs-build" }
nano-rs-extra = { path = "../nano-rs-extra" }
nano-rs-macro = { path = "../nano-rs-macro" }
nano-rs-proc-macro-route = { path = "../nano-rs-proc-macro-route" }

[features]
default = []
mysql = ["nano-rs-extra/mysql"]
postgres = ["nano-rs-extra/postgres"]
utoipa_axum = ["nano-rs-extra/utoipa_axum"]
