port: 8888
name: example
host: 127.0.0.1
base_path:
log:
  enable_request_body_log: true
  level:
    debug:
      file: false
    trace:
      file: false
  logging:
    example:
      level: error
    sqlx:
      level: warn
    tower_http:
      level: error
    hyper:
      level: info
    nano_rs_extra:
      level: info