[package]
edition = "2024"
name = "example_modular"
version = "0.1.0"

[dependencies]
axum = { workspace = true }
axum-client-ip = { workspace = true }
nano-rs = { path = "../nano-rs", features = ["utoipa_axum"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower-http = { workspace = true }
utoipa = { workspace = true }
utoipa-rapidoc = { version = "6.0.0", features = ["axum"] }

example_modular_api = { path = "./api" }
example_modular_layers = { path = "./layers" }
example_modular_model = { path = "./model" }

[build-dependencies]
nano-rs = { path = "../nano-rs", features = ["utoipa_axum"] }
utoipa = { workspace = true }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
