use crate::axum::generator::cache;
#[cfg(feature = "utoipa_axum")]
use crate::axum::generator::parse_utoipa_info;
use crate::axum::generator::write_if_changed;
use proc_macro2::{Span, TokenStream};
use quote::quote;
use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;
use syn::punctuated::Punctuated;
use syn::token::Comma;
use syn::{Attribute, FnArg, ItemUse, LitStr};

use nano_rs_build::api_fn::ApiFn;
use nano_rs_build::api_gen::GenApiInfo;

pub struct AxumGenApiInfo {}

impl GenApiInfo for AxumGenApiInfo {
    fn gen_api_info(
        &self,
        path_buf: PathBuf,
        api_fns: HashMap<
            String,
            ApiFn<String, Punctuated<FnArg, Comma>, Vec<ItemUse>, Vec<Attribute>>,
        >,
        cache_enabled: bool,
    ) {
        eprintln!("gen_api_info in {:?}", path_buf);
        let api_info = path_buf.join(self.get_api_info_file_path());
        #[cfg(feature = "utoipa_axum")]
        let mut api_fns = api_fns;
        #[cfg(feature = "utoipa_axum")]
        for (_name, api_fn) in api_fns.iter_mut() {
            if let Err(err) = parse_utoipa_info(api_fn) {
                panic!("{err}");
            }
        }
        let mut entries: Vec<_> = api_fns.iter().collect();
        entries.sort_by(|(left, _), (right, _)| left.cmp(right));
        let mut fingerprint: Option<String> = None;
        if cache_enabled {
            let mut hasher = std::collections::hash_map::DefaultHasher::new();
            for (key, api_fn) in &entries {
                key.hash(&mut hasher);
                api_fn.method.hash(&mut hasher);
                api_fn.path.hash(&mut hasher);
                api_fn.path_group.hash(&mut hasher);
                api_fn.api_fn_name.hash(&mut hasher);
                api_fn.public.hash(&mut hasher);
                if let Some(api_doc) = &api_fn.api_fn_doc {
                    api_doc.api.hash(&mut hasher);
                    api_doc.api_group.hash(&mut hasher);
                }
            }
            let fingerprint_value = hasher.finish().to_string();
            let cache_hit = cache::read_api_info_hash(path_buf.as_path())
                .ok()
                .filter(|stored| stored == &fingerprint_value)
                .is_some();
            if cache_hit && api_info.exists() {
                return;
            }
            fingerprint = Some(fingerprint_value);
        }

        let mut api_info_vec: Vec<TokenStream> = Vec::new();
        for (_key, api_fn) in entries {
            let method = LitStr::new(api_fn.method.as_str(), Span::call_site());
            let path = LitStr::new(api_fn.path.as_str(), Span::call_site());
            let base_path = LitStr::new(api_fn.path_group.as_str(), Span::call_site());
            let handler_fun = LitStr::new(api_fn.api_fn_name.as_str(), Span::call_site());
            let (summary, group_name) = api_fn
                .api_fn_doc
                .as_ref()
                .map(|doc| {
                    (
                        LitStr::new(doc.api.as_str(), Span::call_site()),
                        LitStr::new(doc.api_group.as_str(), Span::call_site()),
                    )
                })
                .unwrap_or_else(|| {
                    (
                        LitStr::new("", Span::call_site()),
                        LitStr::new("", Span::call_site()),
                    )
                });
            let public = api_fn.public;
            api_info_vec.push(quote! {
                ApiInfo {
                    method: #method.to_owned(),
                    path: #path.to_owned(),
                    base_path: #base_path.to_owned(),
                    handler_fun: #handler_fun.to_owned(),
                    summary: #summary.to_owned(),
                    public: #public,
                    group_name: #group_name.to_owned(),
                }
            });
        }
        let api_info_code: TokenStream = quote!(
            /// Code generated by nano-rs. DO NOT EDIT.
            use nano_rs::axum::generator::gen_api_info::ApiInfo;

            #[allow(dead_code)]
            pub fn get_api_info() -> Vec<ApiInfo> {
                vec![#(#api_info_vec),*]
            }
        );

        let syntax_tree: syn::File = syn::parse2(api_info_code).unwrap();
        let formatted = prettyplease::unparse(&syntax_tree);
        let _ = write_if_changed(api_info.as_path(), formatted.as_str())
            .expect("write api info file failed");
        if cache_enabled {
            if let Some(fingerprint) = fingerprint.as_ref() {
                if let Err(err) = cache::write_api_info_hash(path_buf.as_path(), fingerprint) {
                    eprintln!("failed to persist api info cache: {err}");
                }
            }
        }
        // let output = Command::new("rustfmt")
        //     .arg(api_info.as_path())
        //     .output()
        //     .expect("Failed to execute rustfmt");
        // if !output.status.success() {
        //     eprintln!(
        //         "Rustfmt failed: {}",
        //         String::from_utf8_lossy(&output.stderr)
        //     );
        // }
    }
}

impl AxumGenApiInfo {
    pub fn new() -> Self {
        AxumGenApiInfo {}
    }
}

#[derive(Debug, Clone)]
pub struct ApiInfo {
    pub method: String,
    pub path: String,
    pub base_path: String,
    pub handler_fun: String,
    pub summary: String,
    pub public: bool,
    pub group_name: String,
}
