/// Code generated by nano-rs. DO NOT EDIT.
use utoipa::OpenApi;
#[utoipa::path(
    get,
    path = "/samoyed/{name}",
    tag = "Samoyed",
    summary = "Say Hello to name",
    params(("name" = String, Path)),
    responses(
        (status = 200, body = String),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_0_hello() {}
#[utoipa::path(
    get,
    path = "/samoyed/miss",
    tag = "Samoyed",
    summary = "Miss mantou so much",
    responses(
        (status = 200, body = String),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_1_miss() {}
#[utoipa::path(
    get,
    path = "/samoyed/name",
    tag = "Samoyed",
    summary = "Get Samoyed name",
    responses(
        (status = 200, body = String),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_2_name() {}
#[utoipa::path(
    post,
    path = "/samoyed/shower",
    tag = "Samoyed",
    summary = "Give your Samoyed a bath",
    responses(
        (status = 200, body = crate::types::pet::PetShower),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_3_shower() {}
#[utoipa::path(
    post,
    path = "/store/pet/form",
    tag = "Store",
    summary = "Add a new pet to the store(form)",
    request_body(
        content = crate::model::pet::PetForm,
        content_type = "application/x-www-form-urlencoded"
    ),
    responses(
        (status = 200, body = crate::model::pet::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_4_add_form_pet() {}
#[utoipa::path(
    post,
    path = "/store/pet/json",
    tag = "Store",
    summary = "Add a new pet to the store(json)",
    request_body = crate::model::pet::Pet,
    responses(
        (status = 200, body = crate::model::pet::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_5_add_json_pet() {}
#[utoipa::path(
    get,
    path = "/store/pet/{id}",
    tag = "Store",
    summary = "Get pet by id",
    params(crate::model::pet::Params),
    responses(
        (status = 200, body = crate::model::pet::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_6_get_pet_name() {}
#[utoipa::path(
    get,
    path = "/store/pet/list/{page}/{count}/{id}",
    tag = "Store",
    summary = "Get Pet list by id",
    params(crate::model::pet::Page, crate::model::pet::Params),
    responses(
        (status = 200, body = crate::model::pet::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_7_get_pet_name_list() {}
#[utoipa::path(
    get,
    path = "/store/pet",
    tag = "Store",
    summary = "Query pet by id",
    params(crate::model::pet::QueryPet),
    responses(
        (status = 200, body = crate::model::pet::Pet),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_8_get_query_pet_name() {}
#[utoipa::path(
    get,
    path = "/store/name",
    tag = "Store",
    summary = "Get the default pet store name",
    responses(
        (status = 200, body = String),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_9_get_store_name() {}
#[utoipa::path(
    get,
    path = "/store/tel",
    tag = "Store",
    summary = "Get Store's telephone number",
    responses(
        (status = 200, body = String),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_10_get_store_tel() {}
#[utoipa::path(
    post,
    path = "/store/pet/list/{page}/{count}",
    tag = "Store",
    summary = "Get pet list",
    params(crate::model::pet::Page),
    responses(
        (status = 200, body = Vec<crate::model::pet::Pet>),
        (status = 500, description = "Internal Server Error")
    )
)]
fn __nano_auto_doc_11_pet_page_list() {}
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Pet",
        description = "Pet Api Server",
        version = "v1",
        license(name = "", url = ""),
        contact(name = "Pet", email = "pet@gmail.com", url = ""),
    ),
    paths(
        __nano_auto_doc_0_hello,
        __nano_auto_doc_1_miss,
        __nano_auto_doc_2_name,
        __nano_auto_doc_3_shower,
        __nano_auto_doc_4_add_form_pet,
        __nano_auto_doc_5_add_json_pet,
        __nano_auto_doc_6_get_pet_name,
        __nano_auto_doc_7_get_pet_name_list,
        __nano_auto_doc_8_get_query_pet_name,
        __nano_auto_doc_9_get_store_name,
        __nano_auto_doc_10_get_store_tel,
        __nano_auto_doc_11_pet_page_list
    ),
    components(
        schemas(
            crate::model::pet::InlineThings,
            crate::model::pet::Meta,
            crate::model::pet::Pet,
            crate::model::pet::PetForm,
            crate::types::pet::PetShower
        )
    ),
    servers(
        (url = "", description = "dev"),
        (url = "https://example.com", description = "prod"),
    ),
    tags()
)]
pub struct GenApi {}
